### ISSUE TITLE
Update hook numbers

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/content_access#15]
The updates are numbered in the 2000s. These work fine today, but they could be frustrating problem when people try to upgrade from 1.x to 2.x in 2025 or so. 

We should add a 2002 hook that resets `schema_verison` to `1002`. This would enable future updates to be numbered 1003, and so on.

**Comment by laryn** [comment]
I think I've got an approach that should work. @jenlampton do you think so?

I don't think we can add the rest in a 2002 hook because then the site will keep trying to run the 200x update hooks. But this should reset them to what they should have been in the first place, I think. https://github.com/backdrop-contrib/content_access/pull/17

**Comment by laryn** [comment]
I finally got back to this one and implemented a change suggested by @indigoxela months ago on Zulip -- move this check into `hook_update_last_removed()` which runs on updates and is an unintrusive place to stick this which shouldn't run all the time (like it would in `hook_init` or `hook_requirements`).
