### ISSUE TITLE
Any plans to release this module?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/content_access#4]
What is the status of this project? 

Is https://backdropcms.org/project/simple_access an alternative to this module?

Asking because of this forum question: https://forum.backdropcms.org/forum/restrict-access-content-node

**Comment by simone960** [comment]
I have tested this module these two days and it works very well ! But I need to rebuild the permissions first to get it working. I have also tested "per content node access" function and it works perfectly! I can grant access to each node separately by role(s). I will use it for my current project! 

I think this module is ready to be released so that more people can use it and report if there's other issue which I may not encounter. This is a great module and I used it for several projects with Drupal 7 in the past. It worth to make it available to the community here. Great thanks !

@stpaultim I have tested the "simple access" but it didn't work and it was reported [here](https://github.com/backdrop-contrib/simple_access/issues/7). From what I tested, it should also be able to restrict access per node if it works. However, I will use content access module since it is stable and I am familiar with it. Great thanks !

**Comment by simone960** [comment]
Seems no maintainer for this module. Pity, such a good module... It works well so far on my live project. Hope someone will pick it up and follow up soon.

**Comment by laryn** [comment]
@stpaultim @simone960 I am going to maintain this module. If we can get testers for the latest commits (related to this issue):
https://github.com/backdrop-contrib/content_access/issues/3

...then I think I am ready to make an initial release.

**Comment by simone960** [comment]
Thanks @laryn ! I'm glad you will maintain the module! 

Sure! Let me test it out and let you know but I don't remember I have encountered the related issue you mentioned. May be because I don't use the webform. I will feedback there.

**Comment by laryn** [comment]
I've made a release at this point. Please raise any issues if you come across any.
